### ISSUE TITLE
Vitals HiMemReport: TestHiMemReport... fails with "limit could not be established"

### ISSUE THREAD

**Issue by tstuefe** [SAP/SapMachine#1204] opened 2022-07-20 06:47 UTC
Very rare. In some environments, the automatic limit heuristic seems to fail and we get
```
[0.154s][warning][vitals] Vitals HiMemReport: limit could not be established; will disable high memory reports (specify -XX:HiMemReportMax=<size> to establish a manual limit).
```
Seen two cases in internal tests on linux aarch64 and ppcle.

**Comment by RealCLanger** [comment] 2023-02-10 07:38
Closing because issue did not reproduce for a long time.

**Closed by RealCLanger** 2023-02-10 07:38 UTC
Labels: sapmachineonly
