### ISSUE TITLE
SAP Machine 21, Eclipse 2023-09, ADT - exception

### ISSUE THREAD

**Issue by matthewdjb** [SAP/SapMachine#1517] opened 2023-10-05 05:34 UTC
See here: https://answers.sap.com/questions/13982417/java-exception-creating-new-objects-in-eclipse-202.html

New install of Eclipse Version: 2023-09 (4.29.0) Build id: 20230907-1323 and ADT 3.36.2. Using JRE SAPMachine 21. To replicate the problem, try to create any repository object (E.g. a class) on a SAP System (cloud or on premise), in any package except $TMP.

I get the message:

**java.lang.reflect.InvocationTargetException**

I got the same issue on Eclipse 2023-06. Reverting to SAP Machine 17 resolved the issue, so I'm pretty sure it's a SAP Machine 21 issue.

```
!ENTRY org.eclipse.core.databinding 4 0 2023-10-04 16:50:46.979
!MESSAGE Unhandled exception: java.lang.reflect.InvocationTargetException
!STACK 0
com.sap.adt.compatibility.uritemplate.VariableExpansionException: java.lang.reflect.InvocationTargetException
	at com.sap.adt.compatibility.internal.uritemplate.AdtUriTemplate.expand(AdtUriTemplate.java:33)
	at com.sap.adt.ris.search.internal.RisQuickSearchUriDiscovery.createResourceUriFromTemplate(RisQuickSearchUriDiscovery.java:212)
	at com.sap.adt.ris.search.internal.AdtRepositorySearchService.getURIFromSearchParameters(AdtRepositorySearchService.java:111)
	at com.sap.adt.ris.search.internal.AdtRepositorySearchService.search(AdtRepositorySearchService.java:54)
	at com.sap.adt.ris.search.internal.RisQuickSearch$RisQuickSearchContentProvider.getObjectReferences(RisQuickSearch.java:106)
	at com.sap.adt.ris.search.internal.RisQuickSearch.execute(RisQuickSearch.java:75)
	at com.sap.adt.tools.core.ui.internal.packages.PackageCommonManager.find(PackageCommonManager.java:32)
	at com.sap.adt.tools.core.ui.internal.packages.PackageCommonManager.packageExists(PackageCommonManager.java:55)
	at com.sap.adt.tools.core.ui.internal.packages.PackageServiceUI.packageExists(PackageServiceUI.java:66)
	at com.sap.adt.tools.core.ui.internal.packages.PackageNameBackendValidator.validate(PackageNameBackendValidator.java:44)
	at com.sap.adt.tools.core.ui.internal.packages.PackageNameBackendValidator.validate(PackageNameBackendValidator.java:1)
	at com.sap.adt.tools.core.ui.wizards.NewAdtObjectWizard.validatePropertiesPage(NewAdtObjectWizard.java:760)
	at com.sap.adt.oo.ui.classes.wizards.AbstractNewClassWizard.access$2(AbstractNewClassWizard.java:1)
	at com.sap.adt.oo.ui.classes.wizards.AbstractNewClassWizard$AdtClassWizardDelegate.validate(AbstractNewClassWizard.java:215)
	at com.sap.adt.oo.ui.classes.wizards.AbstractNewClassWizard.validatePropertiesPage(AbstractNewClassWizard.java:89)
	at com.sap.adt.oo.ui.classes.wizards.AbstractNewClassWizard.validatePropertiesPage(AbstractNewClassWizard.java:1)
	at com.sap.adt.tools.core.ui.wizards.NewAdtObjectWizard$9.run(NewAdtObjectWizard.java:1580)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: com.damnhandy.uri.template.impl.VariableExpansionException: java.lang.reflect.InvocationTargetException
	at com.damnhandy.uri.template.DefaultVarExploder.getValue(DefaultVarExploder.java:204)
	at com.damnhandy.uri.template.DefaultVarExploder.initValues(DefaultVarExploder.java:127)
	at com.damnhandy.uri.template.DefaultVarExploder.setSource(DefaultVarExploder.java:98)
	at com.damnhandy.uri.template.DefaultVarExploder.<init>(DefaultVarExploder.java:80)
	at com.damnhandy.uri.template.impl.VarExploderFactory.getExploder(VarExploderFactory.java:41)
	at com.damnhandy.uri.template.impl.RFC6570UriTemplate.expandVariables(RFC6570UriTemplate.java:175)
	at com.damnhandy.uri.template.impl.RFC6570UriTemplate.findExpressions(RFC6570UriTemplate.java:100)
	at com.damnhandy.uri.template.impl.RFC6570UriTemplate.buildVarSpecs(RFC6570UriTemplate.java:527)
	at com.damnhandy.uri.template.impl.RFC6570UriTemplate.expand(RFC6570UriTemplate.java:78)
	at com.sap.adt.compatibility.internal.uritemplate.AdtUriTemplate.expand(AdtUriTemplate.java:29)
	... 17 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.damnhandy.uri.template.DefaultVarExploder.getValue(DefaultVarExploder.java:192)
	... 26 more
Caused by: java.util.NoSuchElementException
	at java.base/java.util.ArrayList.getFirst(ArrayList.java:439)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 28 more
```

**Comment by MBaesken** [comment] 2023-10-05 08:51
btw. I noticed here
https://marketplace.eclipse.org/content/java-21-support-eclipse-2023-09-429
that some additional feature needs to be installed for JDK21 compatibility - are you aware of this feature ?

**Comment by RealCLanger** [comment] 2023-10-05 09:23
> btw. I noticed here https://marketplace.eclipse.org/content/java-21-support-eclipse-2023-09-429 that some additional feature needs to be installed for JDK21 compatibility - are you aware of this feature ?

This probably doesn't have to do with the problem here. The link is what you need when you want to use Java 21 features in Eclipse IDE for Java.

**Comment by RealCLanger** [comment] 2023-10-05 09:25
@matthewdjb Assuming that Eclipse itself runs on JDK 21, I guess this is an issue in ADT. I'm currently trying to connect with the colleagues to find out more...

**Comment by matthewdjb** [comment] 2023-10-05 09:25
Yes, I meand JDK 21. Sorry about that.

**Comment by sratz** [comment] 2023-10-05 10:05
The problem is within ADT (more precisely: within the URI template library dependency used by ADT).

We are working on this.

Until this is resolved, ADT cannot be used with JDK 21.

**Comment by RealCLanger** [comment] 2023-10-05 10:10
Thanks @sratz. With this, I'm closing this ticket. Maybe you can add some further reference here once you have some record for this issue, e.g. an SAP Note.

**Closed by RealCLanger** 2023-10-05 10:10 UTC

**Comment by sratz** [comment] 2023-11-07 15:55
ADT 3.38 (released October 25, 2023, https://me.sap.com/notes/3391753) is now compatible with Java 21.

**Comment by matthewdjb** [comment] 2023-11-07 17:53
Great stuff. Thank you!
