### ISSUE TITLE
App is Crashing After sap machine upgrade

### ISSUE THREAD

**Issue by sulabhrastogi** [SAP/SapMachine#1405] opened 2023-05-16 05:57 UTC
We tried to upgrade the base image we are facing issues. I have attached heap dump for same
https://product-jira.ariba.com/browse/CBLT-23096
[hs_err_pid129.log](https://github.com/SAP/SapMachine/files/11484441/hs_err_pid129.log)

**Comment by RealCLanger** [comment] 2023-05-17 08:19
Hi @sulabhrastogi,

Looking at the hs_err_file, the crash seems to occur in a native library of the netty project. So the likelihood that the issue is with the JDK seems rather small to me. Maybe you should report this to the netty project?

Other than that, since this seems to be a SAP internal issue, I suggest you rather report it in SAP's internal channels, e.g. BCP internal ticket where we could follow up - in case you still feel the need for help from JDK side.

With that I'm closing this ticket. You might reach out to me directly.

Thanks
Christoph

**Closed by RealCLanger** 2023-05-17 08:19 UTC
