### ISSUE TITLE
Hana Admin backup issue

### ISSUE THREAD

**Issue by bi-formance** [SAP/SapMachine#448] opened 2019-07-11 08:46 UTC
Backup execution from Hana Admin perspective is throwing following error:
An internal error occurred during: "Check backup readiness".
javax/xml/soap/SOAPException. Checked on Eclipse 2018-12 as well 2019-06. Latest version of Hana tools (channel https://tools.hana.ondemand.com/2018-09/)
Running Sap machine 11.03.
If I replace SAP machine with Oracle JRE this issue is NOT occurring..

![SapMachine HanaBackup Bug](https://user-images.githubusercontent.com/18594810/61036309-2e2d8580-a3c9-11e9-8da9-0865f3233524.png)

**Comment by RealCLanger** [comment] 2019-07-11 09:13
Hi bi-formance,

thank you for opening this issue.

First question: With which Oracle JRE are you replacing the SapMachine to get your scenario running?
Second question: Do you have some Eclipse error log with more detailed information about the exception?

Best regards
Christoph

**Comment by bi-formance** [comment] 2019-07-11 09:45
Hi Joachim,

Running on Oracle JRE 8U211 solves the issues but also previous releases fixed this.
First observed this early this year, and now thought lets recheck with current SapMachine as I want to get rid of Oracle Java 😊.

Below errorlog excerpt  from Eclipse: (Also added complete Eclipse support file for reference)

!ENTRY org.eclipse.core.jobs 4 2 2019-07-11 10:36:41.816
!MESSAGE An internal error occurred during: "Check backup readiness".
!STACK 0
java.lang.NoClassDefFoundError: javax/xml/soap/SOAPException
               at com.sap.ndb.studio.admin.model.services.impl.ServicesImpl.populate(ServicesImpl.java:741)
               at com.sap.ndb.studio.backup.commands.BackupReadinessJob.run(BackupReadinessJob.java:106)
               at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: javax.xml.soap.SOAPException cannot be found by com.sap.ndb.studio.sapcontrol_2.3.44
               at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
               at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
               at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
               at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
               at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

With Kind Regards, Patrick Rieken.
BI-Formance
Committed to deliver the technical advantage for your SAP BI solution.

T:         +31(0)6-51811866<tel:%2B31%280%296-51811866>
M:        patrick.rieken@bi-formance.nl<mailto:patrick.rieken@bi-formance.nl>
W:        www.bi-formance.nl<http://www.bi-formance.nl/>

**Comment by RealCLanger** [comment] 2019-07-11 09:55
Thanks, Patrick,

I responded to you directly via mail. Maybe it's a Hana studio issue.

Will keep this issue open for now until we've sorted it out...

Cheers
Christoph

**Comment by vtintillier** [comment] 2019-07-11 10:18
Did you try with Orcale JRE 11 ? I would expect the same issue, as those javax packages were removed from the JRE in Java 9 I think.

**Comment by bi-formance** [comment] 2019-07-11 11:32
Hi indeed a JDK 11 issue, Orackle JDK 11 issued the same error, so on the studio part some recoding is needed to be compliant with JDK > 8..

**Comment by xtough** [comment] 2019-07-11 12:25
SAP HANA Studio never officially supported Java >8 --> If you rely on Studio, you will have to stay on Java 8 for now.

**Comment by RealCLanger** [comment] 2019-07-11 13:07
Ok, the issue is understood then (not a SapMachine problem :)). Hence I'm closing it.

**Closed by RealCLanger** 2019-07-11 13:07 UTC
