### ISSUE TITLE
setting TZ variable has no effect when using the docker image

### ISSUE THREAD

**Issue by omichels** [SAP/SapMachine#595] opened 2020-02-07 08:57 UTC
settting the TZ variable e.g. to Europe/Berlin or Europe/Oslo has no effect,
this might be because of all timezone files in /usr/share/timezone are missing

**Comment by RealCLanger** [comment] 2020-02-10 08:47
Hello Oliver,

thanks for reporting this issue. We'll have a look and get back to you soon.

Best regards
Christoph

**Comment by omichels** [comment] 2020-02-10 12:46
well, IMHO the solution is quite easy. tzdata package is lacking the official docker images.
has cost us some weeks of dev/qa effort to discover that bug.
Now we are building the docker images like this:

FROM ${baseImage}
ENV DEBIAN_FRONTEND=noninteractive
RUN if apt-get --version ; then apt-get update ; apt-get -y install tzdata && apt-get clean ; fi

**Comment by reshnm** [comment] 2020-02-11 13:28
Hi @omichels, I tried to reproduce the issue without success.

`docker run -it sapmachine/lts bash`

`$ export TZ="Europe/Berlin"`
`$ jshell`
`jshell> TimeZone.getDefault()`
`$1 ==> sun.util.calendar.ZoneInfo[id="Europe/Berlin",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=143,lastRule=java.util.SimpleTimeZone[id=Europe/Berlin,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]`

Can you please provide steps to reproduce?

Rene

**Comment by omichels** [comment] 2020-02-12 10:07
well, not everything is based on Java

$ docker run -it sapmachine:lts bash
root@2b056731635b:/# date
Wed Feb 12 10:06:43 UTC 2020
root@2b056731635b:/# export TZ="Europe/Berlin"
root@2b056731635b:/# date
Wed Feb 12 10:06:48 Europe 2020
root@2b056731635b:/# export TZ="America/Chicago"
root@2b056731635b:/# date
Wed Feb 12 10:06:52 America 2020

**Comment by RealCLanger** [comment] 2020-02-12 11:34
> well, not everything is based on Java
> 
> $ docker run -it sapmachine:lts bash
> root@2b056731635b:/# date
> Wed Feb 12 10:06:43 UTC 2020
> root@2b056731635b:/# export TZ="Europe/Berlin"
> root@2b056731635b:/# date
> Wed Feb 12 10:06:48 Europe 2020
> root@2b056731635b:/# export TZ="America/Chicago"
> root@2b056731635b:/# date
> Wed Feb 12 10:06:52 America 2020

OK, but that does suggest everything works correctly!? Where is the problem (in that output)?

**Comment by omichels** [comment] 2020-02-12 12:12
> OK, but that does suggest everything works correctly!? Where is the problem (in that output)?

if you are using the date command (libc based binaries), then the time is wrong.


$ docker run -it sapmachine:lts bash
root@6c49a49e3eea:/# export TZ="America/Chicago"
root@6c49a49e3eea:/# date
Wed Feb 12 12:10:23 America 2020
root@6c49a49e3eea:/# jshell
Feb 12, 2020 6:10:26 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
|  Welcome to JShell -- Version 11.0.6
|  For an introduction type: /help intro

jshell> new java.util.Date()
$1 ==> Wed Feb 12 06:10:35 CST 2020

**Comment by reshnm** [comment] 2020-02-13 12:53
The SapMachine Docker images are meant as a starting point on how to use SapMachine within a Docker container or as a base image which can be extended to someones own needs.
We cannot and don't want cover all possible usage scenarios, therefore the image is as small as possible.

> FROM ${baseImage}
ENV DEBIAN_FRONTEND=noninteractive
RUN if apt-get --version ; then apt-get update ; apt-get -y install tzdata && apt-get clean ; fi

This is the correct and intended way to extend the SapMachine image.
As the "missing" tzdata package is not affecting the correct behavior of the SapMachine we won't fix this.

**Closed by reshnm** 2020-02-13 12:53 UTC

**Comment by omichels** [comment] 2020-02-13 14:54
yeah, that makes perfectly sense.
3Mbytes of timezone files will make much of a difference. 

Thanks for nothing

**Comment by RealCLanger** [comment] 2020-02-14 09:07
> yeah, that makes perfectly sense.
> 3Mbytes of timezone files will make much of a difference.
> 
> Thanks for nothing
Da nich für ;-)

But honestly, the sapmachine images should just be basic images. Here is how they are created:
https://github.com/SAP/SapMachine-infrastructure/blob/master/dockerfiles/official/lts/Dockerfile

What's the problem of customizing your usage with the solution you already mentioned.

**Comment by omichels** [comment] 2020-02-26 11:51
>Da nich für

Seriously, get your s... together.

The tzdata is 300KB in total, but having part of the obsolete X11 libs included. Makes perfectly sense to me.

**Comment by reshnm** [comment] 2020-03-02 10:07
I think this discussion isn't getting us anywhere. Therefore I'm locking this discussion and refer to the GitHub community guidelines:

https://help.github.com/en/github/site-policy/github-community-guidelines
