### ISSUE TITLE
Error: An unexpected error occurred while trying to open file

### ISSUE THREAD

**Issue by alumni** [SAP/SapMachine#1450] opened 2023-07-20 10:17 UTC
In version 11.0.20, 17.0.8 or 20.0.2, I get the following error:
```
Error: An unexpected error occurred while trying to open file /opt/wss/wss-unified-agent.jar
```
This was working perfectly on 11.0.19, 17.0.7 or 20.0.1.

The source of the JAR file in my case is: https://github.com/whitesource/unified-agent-distribution/releases/download/v23.5.2.1/wss-unified-agent.jar (however, any version would cause this issue).

Docker image: `node:18.17.0-bookworm-slim`.

**Comment by RealCLanger** [comment] 2023-07-20 12:13
Hi,

from your description it's not quite easy to guess what you are referring to, but maybe it is about usage of the SapMachine docker base images, specifically Ubuntu. We have changed the image a little bit for size optimization. This was the [old Dockerfile](https://github.com/SAP/SapMachine-infrastructure/blob/e87eb6e06a0358b41360780f5ab89656c41a81e3/dockerfiles/official/11/Dockerfile) and here is the [new one](https://github.com/SAP/SapMachine-infrastructure/blob/master/dockerfiles/official/11/ubuntu/jdk/Dockerfile). As you see, the installed packages ca-certificates and gnupg2 along with their dependencies are not part of the base image any more as they were only needed to download and install the sapmachine package.

So, maybe you have been using ca-certificates beforehand inadvertently and now this package is missing? To fix this, you could add the installation of the package to your own custom container build that bases on the SapMachine image?

Best regards
Christoph

**Comment by alumni** [comment] 2023-07-20 12:30
Hi Christoph, I'm building my own Docker image using `node:18.17.0-bookworm-slim` (basically `debian:bookworm-slim` with `node` on top) and manually installing `sapmachine-17-jre` on top:
```sh
apt-get install curl ca-certificates gnupg2
...
apt-get install sapmachine-17-jre=$JAVA_VERSION
```

If I install `sapmachine-17-jre=17.0.8` instead of `sapmachine-17-jre=17.0.7`, the WhiteSource JAR file will stop working. The docker images have nothing do to with it, just that there was a change between 17.0.7 and 17.0.8 that broke WhiteSource.

**Comment by RealCLanger** [comment] 2023-07-20 12:50
OK, then it's maybe a thing in Java - do you have a callstack? I mean, where does "Error: An unexpected error occurred while trying to open file /opt/wss/wss-unified-agent.jar" come from? Is it already during VM startup?

**Comment by FrankReisenhofer** [comment] 2023-07-20 14:00
We found a workaround. Instead of using 3.9-sapmachine-11 we use the docker-image: 3.9.2-sapmachine-11.

**Comment by alumni** [comment] 2023-07-20 14:36
> Can we inspect the wss-unified-agent.jar ?

An older version is in my first message, here is the latest:

https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar

The issue happens in all versions after the last patch update.

**Comment by RealCLanger** [comment] 2023-07-20 21:13
Hi,

we believe the issue is understood. The culprit is a security patch that came with the July update. It is this commit [8300596: Enhance Jar Signature validation](https://github.com/openjdk/jdk/commit/ecd0bc1d6205d1d1eca67cbfb9d4deaeb65739aa). There also exists a [release note](https://www.oracle.com/java/technologies/javase/11-0-20-relnotes.html#JDK-8300596). It adds a limit of 8 MB for jar signature sizes. And the MANIFEST.MF of the jar file that you are using, is larger than that.

So, if you run your Java application with parameter ` -Djdk.jar.maxSignatureFileSize=9000000`, it'll run again without problems.

Cheers
Christoph

**Comment by RealCLanger** [comment] 2023-07-20 21:14
> Local execution is leading to the following error: [1]
> 
> Is this helpful for you?
> 
> [1] Error: An unexpected error occurred while trying to open file .\wss-unified-agent.jar java.io.IOException: Unsupported size: 8577957 for JarEntry META-INF/MANIFEST.MF. Allowed max size: 8000000 bytes at java.base/java.util.jar.JarFile.getBytes(JarFile.java:810) at java.base/java.util.jar.JarFile.getManifestFromReference(JarFile.java:421) at java.base/java.util.jar.JarFile.getManifest(JarFile.java:408) at java.base/sun.launcher.LauncherHelper.getMainClassFromJar(LauncherHelper.java:553) at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:778) at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:686)

How did you get that Exception trace? When I reproduce this locally, I only get the message `Error: An unexpected error occurred while trying to open file .\wss-unified-agent.jar`. But it would have helped if the full exception text would have bubbled up. Maybe there is some room for improvement...

**Comment by FrankReisenhofer** [comment] 2023-07-21 06:43
To address the issue with the Mend unified agent I raised an issue here:

https://github.com/whitesource/unified-agent-distribution/issues/48

**Comment by RealCLanger** [comment] 2023-07-21 07:24
We also created an OpenJDK bug: https://bugs.openjdk.org/browse/JDK-8312489

With that, I'll close this issue. But it's still open for comments.

**Closed by RealCLanger** 2023-07-21 07:24 UTC

**Comment by AlexanderWirthSAP** [comment] 2023-07-24 12:02
Is it possible to apply this setting `jdk.jar.maxSignatureFileSize` to the whitesourceExecuteScan step of the SAP piper pipeline somehow?

**Comment by MBaesken** [comment] 2023-07-24 12:34
Hi Alexander, that's a good question for the Piper colleagues (or the ones that created this 'whitesourceExecuteScan').

I checked the lengthy  docu at https://www.project-piper.io/steps/whitesourceExecuteScan/
but it does not help me to answer this very basic question you asked.
There is a dockerEnvVars  param ('Environment variables to set in the container')  maybe this can be used to sneak in the mentioned system-property via JAVA_OPTIONS.
And what really sounds interesting is the jreDownloadUrl  parameter (you could use that for using an older version of SapMachine , but maybe you already found this); but it is not what you asked for .

**Comment by FrankReisenhofer** [comment] 2023-07-24 12:51
Hello Mathias, hello Alexander,

According to my knowledge the settings can not set from end-users of the piper WhitesourceExecuteScan.

That is why I opened:

https://github.com/SAP/jenkins-library/issues/4481

**Comment by AlexanderWirthSAP** [comment] 2023-07-24 14:13
Thank you Matthias and Frank,

I tried setting the property by setting JAVA_OPTS or JAVA_TOOL_OPTIONS via the [installCommand](https://www.project-piper.io/steps/whitesourceExecuteScan/#installcommand) setting, but it did not seem to work and I'm not sure whether the installCommand even gets executed.

Setting the dockerImage to "maven:3.9.2-sapmachine-17" as suggested by Frank was the easiest workaround so far. If the Jenkins library implements a permanent solution that would be ideal, so thank you for opening the ticket. 😄

**Comment by MBaesken** [comment] 2023-07-31 08:23
There is now an adjustment PR that increases the allowed value from 8000000 to 16000000 
8312489: Increase jdk.jar.maxSignatureFileSize default which is too low for JARs such as WhiteSource/Mend unified agent jar 
https://github.com/openjdk/jdk/pull/15072

**Comment by FrankReisenhofer** [comment] 2023-07-31 11:51
Hello @MBaesken ,

Mend has released a fix: https://github.com/whitesource/unified-agent-distribution/issues/48
