### ISSUE TITLE
SAPMachine11 - Fix Bug JDK-8218889

### ISSUE THREAD

**Issue by 749** [SAP/SapMachine#591] opened 2020-02-03 15:32 UTC
Using SAPMachine11 with SAP Commerce(19.05.9) on linux causes:

`org.apache.tomcat.util.net.NioEndpoint$SocketProcessor doRun
SCHWERWIEGEND: 
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at java.base/sun.security.ssl.ServerHello$T13ServerHelloProducer.produce(ServerHello.java:547)
	at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:436)
	at java.base/sun.security.ssl.ClientHello$T13ClientHelloConsumer.goServerHello(ClientHello.java:1225)
	at java.base/sun.security.ssl.ClientHello$T13ClientHelloConsumer.consume(ClientHello.java:1161)
	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:852)
	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:813)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1048)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:995)
	at org.apache.tomcat.util.net.SecureNioChannel.tasks(SecureNioChannel.java:423)
	at org.apache.tomcat.util.net.SecureNioChannel.handshakeUnwrap(SecureNioChannel.java:483)
	at org.apache.tomcat.util.net.SecureNioChannel.handshake(SecureNioChannel.java:238)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1475)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)`

To appear in the server log.
This appears to be a known issue in the OpenJDK see:
https://bugs.openjdk.java.net/browse/JDK-8218889

Please fix by applying the patch file provided in the OpenJDK Ticket.

**Comment by MSailer** [comment] 2020-02-04 09:22
Hi @749 , thanks for reporting the issue and sorry for any inconvenience caused by this. We shall check the issue and get back to you soon!

**Comment by RealCLanger** [comment] 2020-02-10 08:52
Hello Jan,

at a first glance, the fix for JDK-8218889 seems to be a good candidate for a backport to OpenJDK 11. I'll try to have a look into that.

Best regards
Christoph

**Comment by 749** [comment] 2020-02-10 08:58
Hello Christoph,

thank you for looking into the issue. I'll be looking forward to a fix version

Best regards,
Jan

**Comment by RealCLanger** [comment] 2020-02-14 08:42
Hi,

I've requested a backport to OpenJDK 11u. So I guess it'll be part of 11.0.7, coming in April. Is that sufficient for you or is this a critical issue that would merit an earlier patch?

Cheers
Christoph

**Comment by RealCLanger** [comment] 2020-02-17 10:00
The item has been backported to OpenJDK 11.0.7: https://bugs.openjdk.java.net/browse/JDK-8239075 

So it'll be in the April release of OpenJDK 11.

I'm hence closing this issue.

**Closed by RealCLanger** 2020-02-17 10:00 UTC
Labels: bug

**Comment by 749** [comment] 2020-02-17 15:14
Great work thanks a lot!
